"use client";
import Link from "next/link";
const C={bg:"#09090b",text:"#e4e0d9",textSec:"#9d9890",textDim:"#5c5854",gold:"#c4a265"};
const mono="'IBM Plex Mono',monospace",serif="'Cormorant Garamond',serif",sans="'Raleway',sans-serif";
const H=({children})=><h2 style={{fontSize:18,fontFamily:serif,fontWeight:400,color:C.text,marginTop:32,marginBottom:12}}>{children}</h2>;

export default function DisclaimerPage(){
  return <div style={{minHeight:"100vh",background:C.bg,color:C.text,fontFamily:sans}}>
    <style>{`@keyframes fadeIn{from{opacity:0}to{opacity:1}} a{color:${C.gold}} @media(max-width:768px){.lp{padding:20px!important}}`}</style>
    <nav style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"24px 60px"}}>
      <Link href="/" style={{textDecoration:"none",display:"flex",alignItems:"baseline",gap:3}}><span style={{fontSize:22,fontFamily:serif,fontWeight:300,color:C.gold,letterSpacing:"3px"}}>Spy</span><span style={{fontSize:7,color:C.textDim,fontFamily:mono,letterSpacing:"1.5px"}}>by Atlas</span></Link>
      <Link href="/" style={{fontSize:11,color:C.textDim,textDecoration:"none",fontFamily:mono,letterSpacing:"1px"}}>← Back</Link>
    </nav>
    <div className="lp" style={{maxWidth:780,margin:"0 auto",padding:"20px 60px 80px",animation:"fadeIn 0.5s ease"}}>
      <h1 style={{fontSize:32,fontFamily:serif,fontWeight:300,marginBottom:8}}>Disclaimer</h1>
      <p style={{fontSize:11,fontFamily:mono,color:C.textDim,marginBottom:40}}>Last updated: April 2026</p>
      <div style={{fontSize:14,color:C.textSec,fontWeight:200,lineHeight:1.85}}>
        <H>1. Intelligence Reports</H>
        <p>All intelligence reports, analyses, and assessments generated by Spy by Atlas are produced using artificial intelligence and publicly available open-source data. These reports are for informational purposes only and should not be considered as legal advice, professional security consultation, or definitive fact. While we strive for accuracy, we cannot guarantee the completeness, accuracy, or timeliness of all information contained in our reports.</p>
        <H>2. Not a Licensed Investigation Service</H>
        <p>Spy by Atlas is a technology platform that processes publicly available information. We are not a licensed private investigation firm, law enforcement agency, or legal advisory service. Our reports should not be used as the sole basis for legal, financial, employment, or security decisions. Users requiring certified investigation services should engage licensed professionals in their jurisdiction.</p>
        <H>3. AI-Generated Content</H>
        <p>The Service uses artificial intelligence (Google Gemini) to analyze data and generate reports. AI-generated content may contain inaccuracies, outdated information, or misinterpretations. Users should independently verify critical information before acting on it. We recommend cross-referencing findings with primary sources.</p>
        <H>4. No Guarantee of Security</H>
        <p>While the Service provides security assessments and threat intelligence, we do not guarantee your personal or organizational security. The Service is one component of a comprehensive security posture. We are not liable for any security incidents that occur despite the use of our Service.</p>
        <H>5. Third-Party Data</H>
        <p>The Service references data from publicly available sources including but not limited to social media platforms, public records, news outlets, and academic databases. We do not control the accuracy of third-party data sources and are not responsible for errors in upstream data.</p>
        <H>6. Conflict and Threat Data</H>
        <p>Situation map data and conflict information is sourced from reputable organizations (CFR, ACLED, ICG, ISW) but may not reflect real-time conditions. Do not rely solely on this data for travel or security decisions in conflict zones. Always consult official government travel advisories.</p>
        <H>7. Limitation</H>
        <p>To the fullest extent permitted by applicable law, Atlas Design Institute disclaims all warranties and shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from use of the Service.</p>
      </div>
    </div>
  </div>;
}
